spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      timeout: 2000ms

eureka:
  client:
    enabled: false

management:
  tracing:
    sampling:
      probability: 0.0
