global:
  scrape_interval: 15s

scrape_configs:
  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
          - auth-service:8081
          - user-service:8082
          - intelligence-service:8083
          - project-service:8084
          - notification-service:8085
          - analytics-service:8086

